### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally -- Version 2

### ISSUE THREAD

**Issue by ryanhowa** [timgrossmann/instagram-profilecrawl#115]
I have previously reviewed the issue https://github.com/timgrossmann/instagram-profilecrawl/issues/12 because the error message I receive is the same.

I followed the instructions for installation from the README. I installed python, requirements, chrome, and the chrome driver. Please note I am using the latest version of chrome as of this post. I am also using version 2.44 of the chromedriver.

I'm using Ubuntu 18.04 LTS (was previously using v16 and had the same issue).

I'm executing the following command:
sudo python3 crawl_profile.py USERNAME

And I receive the following error:
Traceback (most recent call last):
  File "crawl_profile.py", line 33, in <module>
    browser = webdriver.Chrome("/home/social/instagram-profilecrawl/assets/chromedriver", options=chrome_options, chrome_options=chromeOptions)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-42-generic x86_64)

Based on the previous issue post, I looked at the crawl_profile.py script for chrome_option additions. I am using the latest commit as of this posting, so all the options suggestions from the previous issue are added to the file.

Still, however, the script fails. 

Does anyone have insight. I've tried different versions of chrome driver and all fail.

**Comment by timmoh** [comment]
could you pls update to latest commit. is there still an error?

**Comment by greyslater** [comment]
Hello @timmoh
I'm on the latest master version but have trouble with the chromedriver

`[WDM] - Current google-chrome version is 71.0.3578
[WDM] - Get LATEST driver version for 71.0.3578
[WDM] - There is no [linux64] chromedriver for browser 71.0.3578 in cache
[WDM] - Get LATEST driver version for 71.0.3578
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/71.0.3578.137/chromedriver_linux64.zip
[WDM] - Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/71.0.3578.137]
Traceback (most recent call last):
  File "crawl_profile.py", line 14, in <module>
    with SetupBrowserEnvironment() as browser:
  File "/home/instagram-profilecrawl/util/chromedriver.py", line 35, in __enter__
    self.browser = init_chromedriver(self.chrome_options, self.capabilities)
  File "/home/instagram-profilecrawl/util/chromedriver.py", line 53, in init_chromedriver
    browser = webdriver.Chrome(ChromeDriverManager().install())
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=71.0.3578.137 (86ee722808adfe9e3c92e6e8ea746ade08423c7e),platform=Linux 4.19.0-9-amd64 x86_64)
`
