### ISSUE TITLE
Reading from a file of list of users and crawling through their basic info

### ISSUE THREAD

**Issue by deenadayalans** [timgrossmann/instagram-profilecrawl#134]
I am trying to get the basic info of a user like name, alias, bio, number of followers, following, posts by giving an input file with list of instagram profiles and implemented it using threads. But I get connection refused error randomly for even a valid profiles as there might be a limit set by the instagram. 

Is there any other way of overcoming it and improve the below code.

```
concurrent = 4

def get_data_and_write_json():
    while True:
        username = q.get()
        print(username)
        browser = init_chromedriver(chrome_options, capabilities)
        information = []
        invalid_users_list = []
        connection_refused_user_list = []
        try:
            information = extract_information(browser,  username, Settings.limit_amount)
        except NoInstaProfilePageFound:
            time.sleep(5)
            print("No profile is found with the user " + username)
            invalid_users_list.append(username)
            Datasaver.save_invalid_profiles_list(username)
    #sys.exit(1)
        except TooManyRequestsError:
            time.sleep(5)
            print("Connection is refused for user " + username)
            connection_refused_user_list.append(username)
            Datasaver.save_connection_refused_users_list(username)

        if username not in invalid_users_list:
            Datasaver.save_profile_json(username,information)

        q.task_done()

        browser.delete_all_cookies()
        browser.quit()        

q = queue.Queue(concurrent * 2)
for i in range(concurrent):
        t = Thread(target=get_data_and_write_json)
        t.daemon = True
        t.start()

try:
    filename = get_input_file_name()
    with open(filename) as inp:
        for ip in inp:
            username = ''
            username_array  = ip[:-1].split("/")
            if username_array[-1] != "":
                username = username_array[-1]
            else:
                username = username_array[-2]
            q.put(username.strip())
        q.join()      

except KeyboardInterrupt:
    browser.quit()
    sys.exit(1)      
```

**Comment by timmoh** [comment]
Which error did you get?

**Comment by deenadayalans** [comment]
I get these Too Many Requests Error (http error code 429) and it skips the profile to the next one. The same error occurs for few valid profiles continuously and the it works normal and so on. Is it something to do with the above code or because of the limit set on the server side.?

**Comment by timmoh** [comment]
"429 Too Many Requests" is the answer. You've been crawling to much with your ipadress on instagram. (which is official not allowed) so they block you.
possible solutions:
- crawl less
- use different interconnection / server
- use proxy


### proxy:
replace 
```python
browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
```
with
```python
proxy_address = "123.456.789.000"
proxy_port = "8080"

prox = Proxy()
proxy = ":".join([proxy_address, proxy_port])
prox.proxy_type = ProxyType.MANUAL
prox.http_proxy = proxy
prox.socks_proxy = proxy
prox.ssl_proxy = proxy
prox.add_to_capabilities(capabilities)
browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
```

**Comment by deenadayalans** [comment]
I tried it but getting below exception,
```

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "crawl_profile.py", line 69, in get_data_and_write_json
    information = extract_information(browser,  username, Settings.limit_amount)
  File "/home/dell/work_deena/instagram-profilecrawl/util/extractor.py", line 226, in extract_information
    web_adress_navigator(browser, user_link)
  File "/home/dell/work_deena/instagram-profilecrawl/util/util.py", line 48, in web_adress_navigator
    WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.ID, "viewport")))
  File "/home/dell/.local/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

```

**Comment by timmoh** [comment]
Specifying 'socksProxy' requires an integer for 'socksVersion'

use proxy_port = 8080 instead of proxy_port = "8080"

**Comment by o365geek** [comment]
Tim, can I use the above proxy setting on Mac?
