### ISSUE TITLE
No module named selenium.common.exceptions

### ISSUE THREAD

**Issue by RDhamala** [timgrossmann/instagram-profilecrawl#157]
Has anybody faced similar issues?

Traceback (most recent call last):
  File "C:\Users\Roshan Dhamala\Independent Class\Insta\instagram-profilecrawl\crawl_profile.py", line 5, in <module>
    from util.datasaver import Datasaver
  File "C:\Users\Roshan Dhamala\Independent Class\Insta\instagram-profilecrawl\util\datasaver.py", line 4, in <module>
    from util.settings import Settings
  File "C:\Users\Roshan Dhamala\Independent Class\Insta\instagram-profilecrawl\util\util.py", line 1, in <module>
    from selenium.common.exceptions import NoSuchElementException
ImportError: No module named selenium.common.exceptions

**Comment by chauhan176** [comment]
Yes i'm also having the same problem.
is this something because of paths?
