### ISSUE TITLE
Having problem crawling a complete profile

### ISSUE THREAD

**Issue by AriaShishegaran** [timgrossmann/instagram-profilecrawl#16]
```
root@ubuntu:/home/aria/instagram-profilecrawl# ./crawl_profile.py behzadshishegaran
Extracting information from behzadshishegaran
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
BEFORE IMG
Traceback (most recent call last):
  File "./crawl_profile.py", line 27, in <module>
    information = extract_information(browser, username)
  File "/home/aria/instagram-profilecrawl/util/extractor.py", line 128, in extract_information
    img, tags, likes, comments = extract_post_info(browser)
  File "/home/aria/instagram-profilecrawl/util/extractor.py", line 68, in extract_post_info
    while (comments[1].text == 'load more comments'):
IndexError: list index out of range

```

the script quits without any extra data on what happened. what's the problem here?

**Comment by tcvieira** [comment]
@AriaShishegaran, could you provide the post url that occurred this error.
I think I know what could have happened and I'll provide a fix.

**Comment by AriaShishegaran** [comment]
for example this profile doesn't work at all.
instagram.com/sara.sarkhosh

**Comment by AriaShishegaran** [comment]
https://www.instagram.com/p/BPdbAZxjpod/

i think it fails to handle empty comment posts?

**Comment by tcvieira** [comment]
Yeap, need to put a check for empty comment posts.

**Comment by timgrossmann** [comment]
#20
