### ISSUE TITLE
Cannot find element - Error on runtime.

### ISSUE THREAD

**Issue by ManchuMakes** [timgrossmann/instagram-profilecrawl#167]
I run this and it returns this.

>>> python3.7 crawl_profile.py lucas_knight._                   

Extracting information from lucas_knight._
INFO [2020-02-15 22:18:23] Extracting information from lucas_knight._
Traceback (most recent call last):
  File "crawl_profile.py", line 21, in <module>
    information, user_commented_list = extract_information(browser, username, Settings.limit_amount)
  File "/Users/lucascomputer/Downloads/instagram-profilecrawl-master/util/extractor.py", line 441, in extract_information
    ig_user.get_user_info()
  File "/Users/lucascomputer/Downloads/instagram-profilecrawl-master/util/extractor.py", line 77, in get_user_info
    self.alias = self._user_alias()
  File "/Users/lucascomputer/Downloads/instagram-profilecrawl-master/util/extractor.py", line 48, in _user_alias
    alias = self.container.find_element_by_class_name('-vDIg').find_element_by_tag_name('h1').text
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 305, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 659, in find_element
    {"using": by, "value": value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"h1"}
  (Session info: headless chrome=80.0.3987.106)

I run, then it just shuts out. Does anyone know there solution (or even problem) to this?

Thanks, Lucas.

**Comment by timmoh** [comment]
is it fixed with the newest pull?
