### ISSUE TITLE
Error on crawl_profile.py

### ISSUE THREAD

**Issue by ineedhacker12345** [timgrossmann/instagram-profilecrawl#176]
INFO [2020-05-12 07:09:01] Extracting information from xxxxxx
Traceback (most recent call last):
  File "crawl_profile.py", line 19, in <module>
    information, user_commented_list = extract_information(browser, username, Settings.limit_amount)
  File "/home/ineedhacker/instagram-profilecrawl/util/extractor.py", line 445, in extract_information
    ig_user = InstagramUser(browser, username)
  File "/home/ineedhacker/instagram-profilecrawl/util/extractor.py", line 34, in __init__
    self.container = self.browser.find_element_by_class_name('v9tJq')
  File "/home/ineedhacker/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/home/ineedhacker/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/ineedhacker/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ineedhacker/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".v9tJq"}
  (Session info: headless chrome=81.0.4044.138)

**Comment by psh0502** [comment]
I have the same problem too.
May I know how you solved it?

**Comment by kbroughton** [comment]
same

**Comment by Joy-liningqiao** [comment]
same
