### ISSUE TITLE
I don't understand what is going wrong?

### ISSUE THREAD

**Issue by amisha-shrivastava** [timgrossmann/instagram-profilecrawl#196]
D:\Projects\instagram-profilecrawl>python crawl_profile.py iaryantiwarii
[WDM] - Downloading: 100%|████████████████████████████████████████████████████████| 6.46M/6.46M [00:01<00:00, 4.02MB/s]

DevTools listening on ws://127.0.0.1:51720/devtools/browser/f194453f-440f-4ac8-8dcb-7c1af6d6877e
Extracting information from iaryantiwarii
INFO [2022-11-11 17:04:37] Extracting information from iaryantiwarii
Traceback (most recent call last):
  File "D:\Projects\instagram-profilecrawl\crawl_profile.py", line 19, in <module>
    information, user_commented_list = extract_information(browser, username, Settings.limit_amount)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\instagram-profilecrawl\util\extractor.py", line 446, in extract_information
    ig_user = InstagramUser(browser, username)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\instagram-profilecrawl\util\extractor.py", line 34, in __init__
    self.container = self.browser.find_element_by_class_name('v9tJq')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Amisha\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Amisha\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Amisha\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Amisha\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".v9tJq"}
  (Session info: chrome=107.0.5304.107)

**Comment by stephen714** [comment]
From what I've found elsewhere online, it could be an issue with the page being incompletely loaded before the next event occurs. I don't know how to fix it though 😞 
I'm also running into this error...

**Comment by 2gethergroup** [comment]
CLASS_NAME changed

In account.py 
44         WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "_ab3b")))
68         WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "_ac8f")))

**Comment by n8petersen** [comment]
Also receiving this error. 
![image](https://github.com/InstaPy/instagram-profilecrawl/assets/6272267/8f4acdf1-3caa-4b20-b4a3-644cc7e65e27)

**Comment by iamyufan** [comment]
Same issue
