### ISSUE TITLE
do this project work yet ? 

### ISSUE THREAD

**Issue by DigexCo** [timgrossmann/instagram-profilecrawl#73]

**Comment by timmoh** [comment]
Could you give us mire informations? (logs, commandline outputs, your config file and so on)

**Comment by DigexCo** [comment]
i run it and messages is 


DevTools listening on ws://127.0.0.1:57058/devtools/browser/5c21363d-9f1a-4ec6-98aa-e3c78d3af863
Waiting 10 sec
Extracting information from behrouz.atoofi
[0710/193005.132:ERROR:ssl_client_socket_impl.cc(1026)] handshake failed; returned -1, SSL error code 1, net_error -101
ok

Url is empty

Error: Couldn't get user profile.
Terminating

**Comment by DigexCo** [comment]
Hi 

now is worked but:

User  instagram  has  0  comments.
[0711/110637.861:WARNING:spdy_session.cc(2961)] Received WINDOW_UPDATE for invalid stream 17
Traceback (most recent call last):
  File "crawl_profile.py", line 33, in <module>
    Datasaver.save_profile_json(username,information)
  File ".\Crawler\util\datasaver.py", line 16, in save_profile_json
    with open(file_profile, 'w') as fp:
OSError: [Errno 22] Invalid argument: '.Crawler\\profiles/instagram_2018-07-11 11:06:37.json'

**Comment by timmoh** [comment]
1) it looks like you are using a old version please update
2) perhaps you have to give the a full qualified path in settings.py

**Comment by DigexCo** [comment]
thanks alot Timmoh 
now it works ...
