### ISSUE TITLE
Script error - chromedriver

### ISSUE THREAD

**Issue by poltys** [timgrossmann/instagram-profilecrawl#8]

**Comment by poltys** [comment]
Hi all,

**Comment by alonecuzzo** [comment]
Yeah I'm getting this error too.

Here's the trace:

```Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "//anaconda/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "//anaconda/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: './assets/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "crawl_profile.py", line 17, in <module>
    browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "//anaconda/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "//anaconda/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home```

**Comment by timgrossmann** [comment]
@poltys @alonecuzzo You have to download the right chromedriver for your system and put it in a `assets` folder.

Look at InstaPy on how it should look like :wink:

**Comment by alonecuzzo** [comment]
thanks!  just finished reading your blog post - cool stuff

**Comment by alonecuzzo** [comment]
@timgrossmann it'd be cool if you added the chromedriver steps into the readme - in the instapy it says to add it in an "assets" folder, but i don't see a similar directory structure in profilecrawl... thx!

**Comment by timgrossmann** [comment]
@alonecuzzo Sorry, I will...
Just add the folder and put the chromedriver in there :wink:

**Comment by alonecuzzo** [comment]
no problem... I created a PR with some instructions if you want to use that ;)

https://github.com/timgrossmann/instagram-profilecrawl/pull/9

**Comment by Stivencannor** [comment]
i can not solve this on windows
