### ISSUE TITLE
No module named settings

### ISSUE THREAD

**Issue by ThomasViennet** [timgrossmann/instagram-profilecrawl#88]
Hi,

Thanks for your script but I have a little problem to run it.

I have two versions of python on OSx
`python -V
Python 2.7.10
`
`python3 -V
Python 3.6.1
`

`python3.6 crawl_profile.py username`
```
Traceback (most recent call last):
  File "crawl_profile.py", line 7, in <module>
    from util.datasaver import Datasaver
  File "/Users/thomasviennet/Desktop/Projects/instagram-profilecrawl/util/datasaver.py", line 5, in <module>
    from .util import check_folder
  File "/Users/thomasviennet/Desktop/Projects/instagram-profilecrawl/util/util.py", line 1, in <module>
    from selenium.common.exceptions import NoSuchElementException
ModuleNotFoundError: No module named 'selenium'
```
`python crawl_profile.py username`
```
Traceback (most recent call last):
  File "crawl_profile.py", line 7, in <module>
    from util.datasaver import Datasaver
  File "/Users/thomasviennet/Desktop/Projects/instagram-profilecrawl/util/datasaver.py", line 4, in <module>
    from util.settings import Settings
ImportError: No module named settings
```

I would like install selenium with "pip3" but I don't understand how to install pip3.

I don't understand this error 
`ImportError: No module named settings`
I run command python crawl_profile.py in the right folder
`ls`
```
LICENSE                        assets                         crawl_profile_pi.py            log_stats.py                   util
README.md                      crawl_profile.py               crawl_profile_without_posts.py stats.csv
```

Can you help me ?

**Comment by timmoh** [comment]
it looks like you haven't installed chrome/selenium please follow instructions
