### ISSUE TITLE
Logging error...

### ISSUE THREAD

**Issue by corncobb** [timgrossmann/instagram-profilecrawl#98]
The crawler semi-works for me but I continuously keep getting this error during crawling which may be the reason why log_stats.py doesn't work for me as well. I tired using Python 3.5 as well and was unsuccessful. Not quite sure what the problem is and this is my traceback during crawling. Any help is greatly appreciated.

`--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 994, in emit
    stream.write(msg)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 151-154: character maps to <undefined>
Call stack:
  File "crawl_profile.py", line 35, in <module>
    information, user_commented_list = extract_information(browser, username, Settings.limit_amount)
  File "C:\Users\Cameron\Desktop\Instagram Crawler\util\extractor.py", line 232, in extract_information
    post_infos, user_commented_total_list = extract_user_posts(browser, num_of_posts_to_do)
  File "C:\Users\Cameron\Desktop\Instagram Crawler\util\extractor.py", line 166, in extract_user_posts
    browser, postlink)
  File "C:\Users\Cameron\Desktop\Instagram Crawler\util\extractor_posts.py", line 105, in extract_post_info
    user_comments, user_commented_list, commentscount = extract_post_comments(browser, post)
  File "C:\Users\Cameron\Desktop\Instagram Crawler\util\extractor_posts.py", line 214, in extract_post_comments
    user_commented[3] + " -- " + comm.find_element_by_tag_name('span').text)`

**Comment by lbenassi** [comment]
Any suggestions on how to solve this error? I tried to run the script `crawl_profile.py` and I get an error similar to the one above

![image](https://user-images.githubusercontent.com/25766101/47484881-1fa03d80-d83d-11e8-8a8a-4827c00417ca.png)

Any help is greatly appreciated, Thanks!
